### PR TITLE
Jepler/2.6/issue 131 lcd

### LINKED ISSUE #131: LCD crashes system calling a page > availible pages
just tested lcd and I found a serious bug

`loadrt lcd fmt_strings="Tool %2d  ZO %7.3f\nX Pos = %8.3f\nY Pos = %8.3f\nZ Pos = %8.3f |Line = %5d\nLength = %5d\nProgress = %3.1f | \n  Machine in ESTOP| \n  Machine ON\n  but not homed"`

My fmt_strings has actually 4 pages, and I can call them with

```
setp lcd.00.page_num 0
setp lcd.00.page_num 1
setp lcd.00.page_num 2
setp lcd.00.page_num 3
```

But if you call setp lcd.00.page_num 4

you get

`rtapi_app: caught signal 11 - dumping core
`

So all crashed, no more reaction etc.

Norbert

### PR DESCRIPTION
**Pull request by jepler**
I believe that this fixes #131.

It's worth noting that as a potential buglet, changes to the pin to control LCD contrast won't be tracked while trying to display an invalid page.  This could be fixed by rearranging the blocks within write_one.

### CODE REVIEW

File: src/hal/components/lcd.c [hunk 1]
```diff
@@ -279,6 +278,8 @@ static void write_one(lcd_inst_t *inst){
         return;
     }    
     
+    if (*inst->page_num >= inst->num_pages) return; // should this error?
+
```
Comment (jepler) [inline src/hal/components/lcd.c]: you'd move this the
~~~~
 if (*inst->contrast != inst->last_contrast){
~~~~
above this early-return if you wanted to track contrast changes while displaying an invalid page.  This is safe, as that if-block doesn't refer to inst->pages[*inst->page_num].

**Comment by jepler** [comment]
@gmoccapy does this PR fix #131 for you?
